---
- name: Update apt package cache
  apt:
    update_cache: yes
  become: yes

- name: Instala pacotes de dependencias do sistema operacional
  apt:
    name: ['mysql-server-8.0', 'python3-mysqldb']
    state: latest
  become: yes 

- name: 'Cria o banco do MySQL'
  mysql_db: 
    name: "{{ wp_db_name }}"
    login_user: root
    state: present            
  become: yes

- name: 'Cria o usuário do MySQL'
  mysql_user:
    login_user: root
    name: "{{ wp_username }}"
    password: "{{ wp_user_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present
    host: "{{ item }}"
  with_items:
    - 'localhost'
    - '127.0.0.1'
    - "{{ wp_host_ip }}"
  become: yes

- name: 'Configura MySQL para aceitar conexões remotas'
  copy:
    src: 'files/mysqld.cnf'
    dest: '/etc/mysql/mysql.conf.d/mysqld.cnf'
  become: yes
  notify:
    - restart mysql 